name: AvoidLib
description: "Yet another library for everything Minecraft. Kinda like Bukkit."
version: "${version}"

main: pl.olafcio.avoid.A4Paper
api-version: '${minecraft_version}'
load: STARTUP

authors: [ Olafcio ]
website: https://github.com/AvoidLib/Avoid/wiki/
bootstrapper: pl.olafcio.avoid.PaperBootstrap

dependencies:
  server: {}
#    packetevents:
#      required: true
#      load: BEFORE
#      join-classpath: true
