package pl.olafcio.avoid.net.item.component;

import net.minecraft.core.Holder;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.tags.TagKey;
import net.minecraft.util.Unit;
import net.minecraft.world.LockCode;
import net.minecraft.world.damagesource.DamageType;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.chicken.ChickenVariant;
import net.minecraft.world.entity.animal.cow.CowVariant;
import net.minecraft.world.entity.animal.cow.MushroomCow;
import net.minecraft.world.entity.animal.equine.Llama;
import net.minecraft.world.entity.animal.equine.Variant;
import net.minecraft.world.entity.animal.feline.CatVariant;
import net.minecraft.world.entity.animal.fish.Salmon;
import net.minecraft.world.entity.animal.fish.TropicalFish;
import net.minecraft.world.entity.animal.fox.Fox;
import net.minecraft.world.entity.animal.frog.FrogVariant;
import net.minecraft.world.entity.animal.nautilus.ZombieNautilusVariant;
import net.minecraft.world.entity.animal.parrot.Parrot;
import net.minecraft.world.entity.animal.pig.PigVariant;
import net.minecraft.world.entity.animal.rabbit.Rabbit;
import net.minecraft.world.entity.animal.wolf.WolfSoundVariant;
import net.minecraft.world.entity.animal.wolf.WolfVariant;
import net.minecraft.world.entity.decoration.painting.PaintingVariant;
import net.minecraft.world.entity.npc.villager.VillagerType;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.*;
import net.minecraft.world.item.alchemy.PotionContents;
import net.minecraft.world.item.component.*;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.enchantment.Enchantable;
import net.minecraft.world.item.enchantment.ItemEnchantments;
import net.minecraft.world.item.enchantment.Repairable;
import net.minecraft.world.item.equipment.Equippable;
import net.minecraft.world.item.equipment.trim.ArmorTrim;
import net.minecraft.world.level.block.entity.BannerPattern;
import net.minecraft.world.level.block.entity.BannerPatternLayers;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.entity.PotDecorations;
import net.minecraft.world.level.saveddata.maps.MapId;
import org.jspecify.annotations.NullMarked;
import pl.olafcio.avoid.annotations.refactor.NeverRemoval;
import pl.olafcio.avoid.net.id.Identification;

import java.util.List;

@NullMarked
@NeverRemoval
public class ItemComponents {
    private ItemComponents() {}

    public static final ItemComponentType<CustomData> CUSTOM_DATA = register("custom_data");
    public static final ItemComponentType<Integer> MAX_STACK_SIZE = register("max_stack_size");
    public static final ItemComponentType<Integer> MAX_DAMAGE = register("max_damage");
    public static final ItemComponentType<Integer> DAMAGE = register("damage");
    public static final ItemComponentType<Unit> UNBREAKABLE = register("unbreakable");
    public static final ItemComponentType<UseEffects> USE_EFFECTS = register("use_effects");
    public static final ItemComponentType<Component> CUSTOM_NAME = register("custom_name");
    public static final ItemComponentType<Float> MINIMUM_ATTACK_CHARGE = register("minimum_attack_charge");
    public static final ItemComponentType<EitherHolder<DamageType>> DAMAGE_TYPE = register("damage_type");
    public static final ItemComponentType<Component> ITEM_NAME = register("item_name");
    public static final ItemComponentType<Identifier> ITEM_MODEL = register("item_model");
    public static final ItemComponentType<ItemLore> LORE = register("lore");
    public static final ItemComponentType<Rarity> RARITY = register("rarity");
    public static final ItemComponentType<ItemEnchantments> ENCHANTMENTS = register("enchantments");
    public static final ItemComponentType<AdventureModePredicate> CAN_PLACE_ON = register("can_place_on");
    public static final ItemComponentType<AdventureModePredicate> CAN_BREAK = register("can_break");
    public static final ItemComponentType<ItemAttributeModifiers> ATTRIBUTE_MODIFIERS = register("attribute_modifiers");
    public static final ItemComponentType<CustomModelData> CUSTOM_MODEL_DATA = register("custom_model_data");
    public static final ItemComponentType<TooltipDisplay> TOOLTIP_DISPLAY = register("tooltip_display");
    public static final ItemComponentType<Integer> REPAIR_COST = register("repair_cost");
    public static final ItemComponentType<Unit> CREATIVE_SLOT_LOCK = register("creative_slot_lock");
    public static final ItemComponentType<Boolean> ENCHANTMENT_GLINT_OVERRIDE = register("enchantment_glint_override");
    public static final ItemComponentType<Unit> INTANGIBLE_PROJECTILE = register("intangible_projectile");
    public static final ItemComponentType<FoodProperties> FOOD = register("food");
    public static final ItemComponentType<Consumable> CONSUMABLE = register("consumable");
    public static final ItemComponentType<UseRemainder> USE_REMAINDER = register("use_remainder");
    public static final ItemComponentType<UseCooldown> USE_COOLDOWN = register("use_cooldown");
    public static final ItemComponentType<DamageResistant> DAMAGE_RESISTANT = register("damage_resistant");
    public static final ItemComponentType<Tool> TOOL = register("tool");
    public static final ItemComponentType<Weapon> WEAPON = register("weapon");
    public static final ItemComponentType<AttackRange> ATTACK_RANGE = register("attack_range");
    public static final ItemComponentType<Enchantable> ENCHANTABLE = register("enchantable");
    public static final ItemComponentType<Equippable> EQUIPPABLE = register("equippable");
    public static final ItemComponentType<Repairable> REPAIRABLE = register("repairable");
    public static final ItemComponentType<Unit> GLIDER = register("glider");
    public static final ItemComponentType<Identifier> TOOLTIP_STYLE = register("tooltip_style");
    public static final ItemComponentType<DeathProtection> DEATH_PROTECTION = register("death_protection");
    public static final ItemComponentType<BlocksAttacks> BLOCKS_ATTACKS = register("blocks_attacks");
    public static final ItemComponentType<PiercingWeapon> PIERCING_WEAPON = register("piercing_weapon");
    public static final ItemComponentType<KineticWeapon> KINETIC_WEAPON = register("kinetic_weapon");
    public static final ItemComponentType<SwingAnimation> SWING_ANIMATION = register("swing_animation");
    public static final ItemComponentType<ItemEnchantments> STORED_ENCHANTMENTS = register("stored_enchantments");
    public static final ItemComponentType<DyedItemColor> DYED_COLOR = register("dyed_color");
    public static final ItemComponentType<MapItemColor> MAP_COLOR = register("map_color");
    public static final ItemComponentType<MapId> MAP_ID = register("map_id");
    public static final ItemComponentType<MapDecorations> MAP_DECORATIONS = register("map_decorations");
    public static final ItemComponentType<MapPostProcessing> MAP_POST_PROCESSING = register("map_post_processing");
    public static final ItemComponentType<ChargedProjectiles> CHARGED_PROJECTILES = register("charged_projectiles");
    public static final ItemComponentType<BundleContents> BUNDLE_CONTENTS = register("bundle_contents");
    public static final ItemComponentType<PotionContents> POTION_CONTENTS = register("potion_contents");
    public static final ItemComponentType<Float> POTION_DURATION_SCALE = register("potion_duration_scale");
    public static final ItemComponentType<SuspiciousStewEffects> SUSPICIOUS_STEW_EFFECTS = register("suspicious_stew_effects");
    public static final ItemComponentType<WritableBookContent> WRITABLE_BOOK_CONTENT = register("writable_book_content");
    public static final ItemComponentType<WrittenBookContent> WRITTEN_BOOK_CONTENT = register("written_book_content");
    public static final ItemComponentType<ArmorTrim> TRIM = register("trim");
    public static final ItemComponentType<DebugStickState> DEBUG_STICK_STATE = register("debug_stick_state");
    public static final ItemComponentType<TypedEntityData<EntityType<?>>> ENTITY_DATA = register("entity_data");
    public static final ItemComponentType<CustomData> BUCKET_ENTITY_DATA = register("bucket_entity_data");
    public static final ItemComponentType<TypedEntityData<BlockEntityType<?>>> BLOCK_ENTITY_DATA = register("block_entity_data");
    public static final ItemComponentType<InstrumentComponent> INSTRUMENT = register("instrument");
    public static final ItemComponentType<ProvidesTrimMaterial> PROVIDES_TRIM_MATERIAL = register("provides_trim_material");
    public static final ItemComponentType<OminousBottleAmplifier> OMINOUS_BOTTLE_AMPLIFIER = register("ominous_bottle_amplifier");
    public static final ItemComponentType<JukeboxPlayable> JUKEBOX_PLAYABLE = register("jukebox_playable");
    public static final ItemComponentType<TagKey<BannerPattern>> PROVIDES_BANNER_PATTERNS = register("provides_banner_patterns");
    public static final ItemComponentType<List<ResourceKey<Recipe<?>>>> RECIPES = register("recipes");
    public static final ItemComponentType<LodestoneTracker> LODESTONE_TRACKER = register("lodestone_tracker");
    public static final ItemComponentType<FireworkExplosion> FIREWORK_EXPLOSION = register("firework_explosion");
    public static final ItemComponentType<Fireworks> FIREWORKS = register("fireworks");
    public static final ItemComponentType<ResolvableProfile> PROFILE = register("profile");
    public static final ItemComponentType<Identifier> NOTE_BLOCK_SOUND = register("note_block_sound");
    public static final ItemComponentType<BannerPatternLayers> BANNER_PATTERNS = register("banner_patterns");
    public static final ItemComponentType<DyeColor> BASE_COLOR = register("base_color");
    public static final ItemComponentType<PotDecorations> POT_DECORATIONS = register("pot_decorations");
    public static final ItemComponentType<ItemContainerContents> CONTAINER = register("container");
    public static final ItemComponentType<BlockItemStateProperties> BLOCK_STATE = register("block_state");
    public static final ItemComponentType<Bees> BEES = register("bees");
    public static final ItemComponentType<LockCode> LOCK = register("lock");
    public static final ItemComponentType<SeededContainerLoot> CONTAINER_LOOT = register("container_loot");
    public static final ItemComponentType<Holder<SoundEvent>> BREAK_SOUND = register("break_sound");
    public static final ItemComponentType<Holder<VillagerType>> VILLAGER_VARIANT = register("villager/variant");
    public static final ItemComponentType<Holder<WolfVariant>> WOLF_VARIANT = register("wolf/variant");
    public static final ItemComponentType<Holder<WolfSoundVariant>> WOLF_SOUND_VARIANT = register("wolf/sound_variant");
    public static final ItemComponentType<DyeColor> WOLF_COLLAR = register("wolf/collar");
    public static final ItemComponentType<Fox.Variant> FOX_VARIANT = register("fox/variant");
    public static final ItemComponentType<Salmon.Variant> SALMON_SIZE = register("salmon/size");
    public static final ItemComponentType<Parrot.Variant> PARROT_VARIANT = register("parrot/variant");
    public static final ItemComponentType<TropicalFish.Pattern> TROPICAL_FISH_PATTERN = register("tropical_fish/pattern");
    public static final ItemComponentType<DyeColor> TROPICAL_FISH_BASE_COLOR = register("tropical_fish/base_color");
    public static final ItemComponentType<DyeColor> TROPICAL_FISH_PATTERN_COLOR = register("tropical_fish/pattern_color");
    public static final ItemComponentType<MushroomCow.Variant> MOOSHROOM_VARIANT = register("mooshroom/variant");
    public static final ItemComponentType<Rabbit.Variant> RABBIT_VARIANT = register("rabbit/variant");
    public static final ItemComponentType<Holder<PigVariant>> PIG_VARIANT = register("pig/variant");
    public static final ItemComponentType<Holder<CowVariant>> COW_VARIANT = register("cow/variant");
    public static final ItemComponentType<EitherHolder<ChickenVariant>> CHICKEN_VARIANT = register("chicken/variant");
    public static final ItemComponentType<EitherHolder<ZombieNautilusVariant>> ZOMBIE_NAUTILUS_VARIANT = register("zombie_nautilus/variant");
    public static final ItemComponentType<Holder<FrogVariant>> FROG_VARIANT = register("frog/variant");
    public static final ItemComponentType<Variant> HORSE_VARIANT = register("horse/variant");
    public static final ItemComponentType<Holder<PaintingVariant>> PAINTING_VARIANT = register("painting/variant");
    public static final ItemComponentType<Llama.Variant> LLAMA_VARIANT = register("llama/variant");
    public static final ItemComponentType<Axolotl.Variant> AXOLOTL_VARIANT = register("axolotl/variant");
    public static final ItemComponentType<Holder<CatVariant>> CAT_VARIANT = register("cat/variant");
    public static final ItemComponentType<DyeColor> CAT_COLLAR = register("cat/collar");
    public static final ItemComponentType<DyeColor> SHEEP_COLOR = register("sheep/color");
    public static final ItemComponentType<DyeColor> SHULKER_COLOR = register("shulker/color");

    public static <T> ItemComponentType<T> register(String id) {
        return new ItemComponentType<>() {
            @Override
            public Identification getId() {
                return Identification.of(id);
            }
        };
    }
}
