license="Apache License 2.0"
issueTrackerURL="https://github.com/AvoidLib/Avoid/issues"

[[mods]]
modId="avoid_processor"
version="1.0"
displayName="AvoidLib (Processor)"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display

# A text field displayed in the mod UI
#credits="" #optional

# The authors of the mod, displayed in the mod UI (optional)
authors="Olafcio"

# The description text for the mod (multi line!) (#mandatory)
description='''
Yet another library for everything Minecraft. Kinda like Bukkit.
'''
